### ISSUE TITLE
Bloqueo de cloudflare

### ISSUE THREAD

**Issue by GuabinaCore** [elpatronaco/pccomponentes-buy-bot#1]
Al parecer la pagina de pccomponentes esta bloqueando el bot al abrir por primera vez no llega no logea ni nada simplemente se queda en el mensaje de chequeando tu explorador

**Comment by opiumcloud** [comment]
estás accediendo desde una IP española?

**Comment by elpatronaco** [comment]
Vaya, a mí no me pasa. Si te han bloqueado (que no creo porque desarrollando el bot lo he hecho correr 100 veces como mínimo) podrías tratar de usar una vpn con ip española como dice @opiumcloud. Comprueba también que la versión de chrome sea la misma que la del chromedriver. Si pudieras acompañar alguna foto mejor
