### ISSUE TITLE
Error lanzamiento del navegador

### ISSUE THREAD

**Issue by RodrigoTomeES** [elpatronaco/pccomponentes-buy-bot#13]
Hola buenas,

Estoy intentando ejecutar el bot en una raspberry pi 4 con Raspbian Lite y me esta dando este error:

![imagen](https://user-images.githubusercontent.com/13077343/111030228-5de42a80-8401-11eb-9339-7cb4b7c366eb.png)

He instalado los requirimientos asi:

# Node
```
curl -sL https://deb.nodesource.com/setup_15.x | sudo -E bash -
sudo apt install nodejs
```

# NPM
```
sudo apt install npm
```

# Chromium
```
sudo apt install chromium-browser
```

# ChromeDriver
```
wget -N https://chromedriver.storage.googleapis.com/88.0.4324.96/chromedriver_linux64.zip -P ~/
unzip ~/chromedriver_linux64.zip -d ~/
rm ~/chromedriver_linux64.zip
sudo mv -f ~/chromedriver /usr/local/bin/chromedriver
sudo chown root:root /usr/local/bin/chromedriver
sudo chmod 0755 /usr/local/bin/chromedriver
```

Actualizo el issue, he caído en que había instalado las dependencias antes de instalar todos los requerimientos. Las he desinstalado y vuelto a instalar y ahora el error es este:

![Screenshot_20210313_143332.jpg](https://user-images.githubusercontent.com/13077343/111031709-27121280-8409-11eb-8d28-07ffbc3e44be.jpg)

Intuyo que el bot solo es compatible con la versión 85? Tengo la versión 88 instalada, voy a intentar instalar la versión 85.

**Comment by elpatronaco** [comment]
No es un issue del bot, es un problema de dependencias. Mírate este hilo https://github.com/puppeteer/puppeteer/issues/807

**Comment by RodrigoTomeES** [comment]
> No es un issue del bot, es un problema de dependencias. Mírate este hilo https://github.com/puppeteer/puppeteer/issues/807

Muchas gracias ahora miro

**Comment by RodrigoTomeES** [comment]
> 
> 
> No es un issue del bot, es un problema de dependencias. Mírate este hilo [puppeteer/puppeteer#807](https://github.com/puppeteer/puppeteer/issues/807)

Hola he estado mirando el issue que me comentas y no consigo que funcione, me puedes echar una mano?
