### ISSUE TITLE
Problema con PcComponentes y Coolmod

### ISSUE THREAD

**Issue by franVR10** [elpatronaco/pccomponentes-buy-bot#18]
Problema con PcComponentes:

![image](https://user-images.githubusercontent.com/80314582/111914310-b8206380-8a71-11eb-86b2-6ece8a88b438.png)

Problema con Coolmod:

![image](https://user-images.githubusercontent.com/80314582/111914358-e30ab780-8a71-11eb-8221-4882f9bbdb7c.png)

LDLC parece funcionar bien.

**Comment by elpatronaco** [comment]
Raro, has reinstalado dependencias ¿? (npm i)

**Comment by franVR10** [comment]
Sii

**Comment by elpatronaco** [comment]
Ya lo he arreglado, vuelve a probar

**Comment by franVR10** [comment]
Me sigue fallando. Al hacer de nuevo la instalación me esta dando varios warnings:

![image](https://user-images.githubusercontent.com/80314582/111961586-851db480-8af1-11eb-8f40-d584cbb0a063.png)

**Comment by elpatronaco** [comment]
Ni caso a eso

**Comment by franVR10** [comment]
Pues ahora funciona tanto pccomponentes como ldlc pero coolmod me sigue diciendo lo mismo de la segunda captura

**Comment by elpatronaco** [comment]
Ya está

**Comment by franVR10** [comment]
Lo he vuelto a reinstalar y tal y parece que no. Mismo error en coolmod :x

**Comment by elpatronaco** [comment]
Mmmm el de **Execution context was destroyed** ? Déjame mirar, a mí ya no me estaba dando error :/

**Comment by franVR10** [comment]
Sii

![image](https://user-images.githubusercontent.com/80314582/111971813-0a5a9680-8afd-11eb-84bd-88dc426cfac1.png)

**Comment by franVR10** [comment]
He visto un chaval que te ha comentado hace nada y a él no le ha dado error haciendo login, y a ti tampoco te da error. Alguna idea de que me podría estar fallando a mi ?

Version de node quizás?

**Comment by RodrigoTomeES** [comment]
> 
> 
> Sii
> 
> ![image](https://user-images.githubusercontent.com/80314582/111971813-0a5a9680-8afd-11eb-84bd-88dc426cfac1.png)

Igual lo tienes en modo debug y has cerrado sin querer la pestaña de chromium?

Ese error me dio a mi cuanto estaba debugeando el código y sin querer cerre la pestaña, pero es normal si es por eso ya que te has cargado el navegador que usa el bot

**Comment by franVR10** [comment]
{
   "pccomponentes": {
    "email": "",
    "password": "",
    "items": [
      {
        "link": "https://www.pccomponentes.com/zotac-gaming-geforce-rtx-3080-trinity-oc-10gb-gddr6x",
        "maxPrice": 980
      }
    ]
  },
  "ldlc": {
    "email": "",
    "password": "",
    "items": [
      {
        "link": "https://www.ldlc.com/es-es/ficha/PB00375644.html",
        "maxPrice": 980
      }
    ]
  },

 "coolmod": {
    "email": "",
    "password": "",
    "items": [
      {
        "link": "https://www.coolmod.com/evga-geforce-rtx-3080-xc3-black-gaming-10gb-gddr6x-tarjeta-grafica-precio",
        "maxPrice": 980
      }
    ]
  },

  "onlyOneBuy": true,
  "debug": false,
  "refreshRate": 3000,
  "browserOptions": {
    "headless": {
      "headless": true,
      "defaultViewport": null,
      "ignoreHTTPSErrors": "true",
      "args": [
        "--no-sandbox",
        "--disable-setuid-sandbox",
        "--disable-infobars",
        "--window-position=0,0",
        "--ignore-certifcate-errors",
        "--ignore-certifcate-errors-spki-list",
        "--user-agent=\"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3312.0 Safari/537.36\""
      ]
    },
    "debug": {
      "headless": false,
      "args": ["--start-maximized"],
      "defaultViewport": null
    }
  }
}

Eso es lo que tengo pero con emails y contraseñas puestos, no se si estoy ciego y me he tragado algún paréntesis o llave o he puesto algo y no lo veo jaja. Estoy rayadisimo, con este bot no me ha funcionado coolmod en ninguna de las versiones que llevas subidas no lo entiendo :X

**Comment by elpatronaco** [comment]
._.XD, voy a pegarle un repaso a los logins pero a mí no me da ese fallo
![image](https://user-images.githubusercontent.com/38383754/111976789-4e9c6580-8b02-11eb-8692-05b265d96de7.png)

**Comment by elpatronaco** [comment]
@RodrigoTomeES Creo q el error del Execution context pasa cuando almacenas un elemento en una variable y cuando quieres pulsar en ella, hacer un focus o cualquier vaina ya no está en la página, tipo
```javascript
const foo = await page.$(".foo")
// cambia de página
await foo.click()
```

**Comment by elpatronaco** [comment]
Prueba ahora @franVR10

**Comment by RodrigoTomeES** [comment]
Si tiene toda la pinta, ya que implica lo mismo, que se ha destruido un elemento que estaba usando

**Comment by franVR10** [comment]
![image](https://user-images.githubusercontent.com/80314582/111979164-06cb0d80-8b05-11eb-9a07-60127716216e.png)

Ahora no me sale ningún error de que se destruya el contexto. Sale que mi logging está mal pero lo he comprobado y si están bien los datos

**Comment by elpatronaco** [comment]
joder 😂 ya no sé que intentar, en el data.json pon 
```json
{
    "debug": true
}
```
y mira a ver qué hace

**Comment by franVR10** [comment]
No entiendo nada. Con el debug true, me loguea en coolmod sin problemas

**Comment by RodrigoTomeES** [comment]
Igual esta saltando alguna protección anti bots y cuando eso no puede hacer login?

**Comment by franVR10** [comment]
Tiene que ser algo de eso. Me ha dado error haciendo con debug false de nuevo. Y en true no me ha dado ni un solo fallo todavía. Aunque bueno os estoy hablando sin saber mucho jaja

**Comment by elpatronaco** [comment]
Hahaha lo raro de los programas es que funcionen, doy por cerrado esto, si te vuelve a pasar esto reabre el issue o crea otro. Mersi!
