### ISSUE TITLE
"npm WARN @cliqz/adblocker-puppeteer@1.18.7 requires a peer of puppeteer@5.x"

### ISSUE THREAD

**Issue by golias2k** [elpatronaco/pccomponentes-buy-bot#23]
Having this issue i dont know how to fix it. Im using a Windows machine already got Node installed etc. When i do NPM Install it installs everything but not this. 

"C:\pccomponentes-buy-bot-master\node_modules>npm install
npm WARN @cliqz/adblocker-puppeteer@1.18.7 requires a peer of puppeteer@5.x but none is installed. You must install peer dependencies yourself."

**Comment by RodrigoTomeES** [comment]
That is a warning and the bot should work (I think). Have you tried to run it?

**Comment by elpatronaco** [comment]
There's no problem at all, this has already been fixed (refer to [this issue](https://github.com/berstend/puppeteer-extra/issues/370)). Try the bot and report any problems you find

**Comment by golias2k** [comment]
Im running it Right now. Also can u tell me if i can have multiple items ? How i edit so it searches for lets say 5 items?

**Comment by RodrigoTomeES** [comment]
You can add more items to the array
```JSON
"pccomponentes": {
  "email": "amador@gmail.com",
  "password": "mariscosrecio",
  "items": [
    {
      "link": "https://www.pccomponentes.com/xiaomi-mi-computer-monitor-light-bar?gclid=Cj0KCQiAhP2BBhDdARIsAJEzXlFGPt39wcTtyjo0deaBkYmMFp7w0uHrSrSwFlMSCJzVJIUCZZYrQs0aAvfzEALw_wcB&",
      "maxPrice": 3000
    },
    {
      "link": "https://www.pccomponentes.com/xiaomi-mi-computer-monitor-light-bar?gclid=Cj0KCQiAhP2BBhDdARIsAJEzXlFGPt39wcTtyjo0deaBkYmMFp7w0uHrSrSwFlMSCJzVJIUCZZYrQs0aAvfzEALw_wcB&",
      "maxPrice": 3000
    },
    {
      "link": "https://www.pccomponentes.com/xiaomi-mi-computer-monitor-light-bar?gclid=Cj0KCQiAhP2BBhDdARIsAJEzXlFGPt39wcTtyjo0deaBkYmMFp7w0uHrSrSwFlMSCJzVJIUCZZYrQs0aAvfzEALw_wcB&",
      "maxPrice": 3000
    }
  ]
}
```

**Comment by golias2k** [comment]
thanks brother! i have to "close )}] the commands. Im new to coding
