### ISSUE TITLE
Intento añadir segundo item en misma tienda y no me deja.

### ISSUE THREAD

**Issue by itsjdfa** [elpatronaco/pccomponentes-buy-bot#25]
No encuentro como añadir para que busque 2 graficas en la misma tienda...

Lo tengo tal que así:

 "pccomponentes": {
    "email": "**",
    "password": "**",
    "items": [
      {
        "link": "https://www.pccomponentes.com/zotac-geforce-rtx-3060ti-d6-twin-edge-oc-8gb-gddr6-reacondicionado",
        "maxPrice": 440
      }
	  {
        "link": "https://www.pccomponentes.com/zotac-geforce-rtx-3060ti-d6-twin-edge-oc-8gb-gddr6",
        "maxPrice": 440
      }
	  {
        "link": "https://www.pccomponentes.com/msi-rtx-3060-ti-ventus-2x-oc-8gb-gddr6",
        "maxPrice": 440
      }
	  {
        "link": "https://www.pccomponentes.com/msi-rtx-3060-ti-ventus-2x-oc-8gb-gddr6-reacondicionado",
        "maxPrice": 440
      }
    ]
  },
  
  
  Seguro que hay algo que estoy haciendo mal pero no se lo que puede ser, al intentar activarlo me lanza este error:
  
SyntaxError: C:\Users\jesus\Desktop\pccomponentes-buy-bot-master\src\data.json: Unexpected token { in JSON at position 267
    at parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:1106:22)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\jesus\Desktop\pccomponentes-buy-bot-master\src\scripts\app.js:6:14)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! buy-bot@1.0.0 start: `node src`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the buy-bot@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by elpatronaco** [comment]
Tienes el json mal, vuelve a descargártelo. Entonces en el apartado de cada tienda tienes que apilar los links, tipo
```json
{
  "pccomponentes": {
    "email": "jajajaja",
    "password": "ungaunga",
    "items": [
      {
        "link": "https://www.pccomponentes.com/xiaomi-mi-computer-monitor-light-bar?gclid=Cj0KCQiAhP2BBhDdARIsAJEzXlFGPt39wcTtyjo0deaBkYmMFp7w0uHrSrSwFlMSCJzVJIUCZZYrQs0aAvfzEALw_wcB&",
        "maxPrice": 3000
      },
      {
        "link": "https://www.pccomponentes.com/xiaomi-mi-computer-monitor-light-bar?gclid=Cj0KCQiAhP2BBhDdARIsAJEzXlFGPt39wcTtyjo0deaBkYmMFp7w0uHrSrSwFlMSCJzVJIUCZZYrQs0aAvfzEALw_wcB&",
        "maxPrice": 3000
      },
      {
        "link": "https://www.pccomponentes.com/xiaomi-mi-computer-monitor-light-bar?gclid=Cj0KCQiAhP2BBhDdARIsAJEzXlFGPt39wcTtyjo0deaBkYmMFp7w0uHrSrSwFlMSCJzVJIUCZZYrQs0aAvfzEALw_wcB&",
        "maxPrice": 3000
      }
    ]
  },
  ...
}

```
Si no tienes ningún editor de codigo, puedes validar el JSON [aquí](https://jsonlint.com/) por ejemplo. El código que te he pasado arriba para cada tienda, si no quieres buscar en esa tienda no pongas nada, borralo

**Comment by itsjdfa** [comment]
Corregido, me faltaban unas comas en el JSON y he descargado el JSON que daba error y solucionado, muchas gracias!

**Comment by elpatronaco** [comment]
de nada 🤙
