### ISSUE TITLE
Un pregunta, ¿como funciona la compra?

### ISSUE THREAD

**Issue by Typebrey** [elpatronaco/pccomponentes-buy-bot#26]
Mi duda es, ¿es automática? porque en mi caso a mi me envía un pin al móvil mientras la compro, entonces no se si la podrá comprar automáticamente sin necesidad de que yo tenga que intervenir.

Quiero decir que me parecéis unos cracks creado esto, muchas gracias por todo!

**Comment by elpatronaco** [comment]
Bueenas, a qué tienda te refieres? En todas las tiendas compra por transferencia bancaria, no tarjeta. Y a lo segundo de nada  :)

**Comment by Typebrey** [comment]
Si el bot hace todo automáticamente sin necesidad de que yo intervenga en algo, pero ya me quedo claro con tu respuesta jaja, muchísimas gracias por el soporte maquina. <3
