### ISSUE TITLE
No compra en pccomponentes

### ISSUE THREAD

**Issue by elguitarrazo** [elpatronaco/pccomponentes-buy-bot#27]
En pccomponentes, se queda marcando y desmarcando la casilla de "entiendo y acepto las condiciones de envío y facturación." y no termina la compra.

**Comment by elpatronaco** [comment]
tienes ```debug: true``` en el data.json ?

**Comment by elguitarrazo** [comment]
Si, para ver si hacia la compra bien, ya lo he solucionado quitando el if de `if (!data.debug) await page.$eval('#GTM-carrito-finalizarCompra', el => el.click())` , repite unas pocas veces el bucle y compra.
