### ISSUE TITLE
Doble Problema

### ISSUE THREAD

**Issue by GuabinaCore** [elpatronaco/pccomponentes-buy-bot#5]
Buenas @elpatronaco hoy probando el bot al parecer no hay manera que me funcione. Poniendo la tarjeta de credito en el bot para que lo rellene el, no lanza ningun error pero a la hora de marcar la casilla de "Entiendo y acepto..." la marca y desmarca infinitas veces y no termina el proceso.

Ahora si no pongo ninguna tarjeta de credito y si no tengo ninguna tarjeta de credito en mi cuenta ya agregada deberia seleccionar la opcion de pago por transferencia pero me salta el siguiente error:

![image](https://user-images.githubusercontent.com/42710853/106267734-5e967800-622a-11eb-881a-9aa8820b3a2b.png)

**Comment by elpatronaco** [comment]
Ahora mismo estoy currando, más tarde lo miro, pero tiene pinta de que el botón no está dentro de la pantalla y no puede pulsarlo

**Comment by GuabinaCore** [comment]
Es posible que sea eso... no hace scroll hasta tan abajo parece y queda hasta ahi al momento de tirar el error

![image](https://user-images.githubusercontent.com/42710853/106279312-80005f80-623c-11eb-9c31-f829c320f16f.png)
