### ISSUE TITLE
Error en pago con nueva version

### ISSUE THREAD

**Issue by Alexcruzgar** [elpatronaco/pccomponentes-buy-bot#8]
Buenos dias,

Lo primero de todo, darte las gracias por compartir tu trabajo con todos nosotros.

He realizado una prueba con la ultima version del bot, y al encontrar el producto en stock, me ha mostrado el mensaje adjunto.
![Codigo](https://user-images.githubusercontent.com/79900153/109616527-892f6580-7b35-11eb-8db7-1fd5d451f343.jpg)

El pedido se ha completado correctamente, pero ha seleccionado el pago por financiacion 12 meses en vez de por transferencia bancaria.

![Pedido1](https://user-images.githubusercontent.com/79900153/109616533-8c2a5600-7b35-11eb-89e3-ec20ae66f3cb.jpg)
![Pedido2](https://user-images.githubusercontent.com/79900153/109616534-8cc2ec80-7b35-11eb-89fa-3404acdc1ed6.jpg)

¿Estoy haciendo algo mal? Utilizo git 2.30 en Windows

Muchas gracias.

**Comment by elpatronaco** [comment]
Te lo miro.

**Comment by elpatronaco** [comment]
Raro. Me lo selecciona bien. Lo estás corriendo en headless no? (modo consola)
![image](https://user-images.githubusercontent.com/38383754/109620161-da415880-7b39-11eb-96d3-59952e97731b.png)

**Comment by Alexcruzgar** [comment]
Lo he corrido desde Git cmd, y en ningun momento he visto nada (en la version anterior del bot se me abria Chrome y veia como iba dando los pasos).

**Comment by elpatronaco** [comment]
Comprueba ahora si funciona, antes de correrlo pon el comando ```npm install```, he añadido otro paquete

**Comment by elpatronaco** [comment]
Si quieres ver la ventana para ver lo que hace el bot en todo momento, en el archivo **index.js** tienes que poner **debug: true**, pero no le dará al botón de comprar al final, lo uso para buscar errores

**Comment by Alexcruzgar** [comment]
Ahora funciona perfecto. Muchisimas gracias. Si algun dia consigo comprar una grafica para mi pc estas invitado a una caña ;)

**Comment by elpatronaco** [comment]
Hahaha de nada tio, gracias por avisar del error
