### ISSUE TITLE
problema con tarjeta

### ISSUE THREAD

**Issue by itsjdfa** [elpatronaco/pccomponentes-buy-bot#9]
He intentado pagar con la tarjeta un producto aleatorio para ver si funciona pero aunque la cuenta tenga una tarjeta añadida o que yo se la indique en el index siempre me selecciona transferencia bancaria, estoy haciendo algo mal?

**Comment by elpatronaco** [comment]
Al iniciar el bot he puesto un mensaje en el que pongo que no está habilitado de momento, estoy trabajando en el paso de añadir tarjeta, pero lo más seguro es que no lo ponga y sólo ponga pago por transferencia, porque con puppeteer es más difícil cambiar entre los iFrames en los que está cada input. Si quieres pago con tarjeta te tendrás que bajar el proyecto antes de migrar a puppeteer, en [este commit](https://github.com/elpatronaco/pccomponentes-buy-bot/commit/209e5b9705cefa78d3cb68cefff708f0594af2cc)

**Comment by itsjdfa** [comment]
Vale, entonces no hay problema, supongo que al marcar pago por transferencia el pedido queda como "reservado" cierto? o supone algun problema a la hora de realizar el pedido?

**Comment by elpatronaco** [comment]
Ninguno, queda a la espera de que hagas el pago, y si no lo haces se cancela el pedido. Pero que va que va, va igual de bien que el pago con tarjeta

**Comment by itsjdfa** [comment]
Pues si no hay ningun problema entonces perfecto! Gracias por aclararme un poco la cosa!
